#pragma once

#define VERSIONINFO_MAJORVERSION 1
#define VERSIONINFO_MINORVERSION 3
#define VERSIONINFO_BUGFIXVERSION 2

#define VERSIONINFO_COPYRIGHT_YEAR "2026"
#define VERSIONINFO_COPYRIGHT_NAME "Anthony Kleine"

#define VERSIONINFO_FILE_DESCRIPTION "Myst IV: Revolution"
#define VERSIONINFO_COMPANY_NAME "TOMYSSHADOW"
#define VERSIONINFO_PRODUCT_NAME "M4Revolution"
#define VERSIONINFO_FILE_NAME VERSIONINFO_PRODUCT_NAME ".exe"

#define _VERSIONINFO_STR2(x) #x
#define _VERSIONINFO_STR(x) _VERSIONINFO_STR2(x)

#define VERSIONINFO_VERSION \
	_VERSIONINFO_STR(VERSIONINFO_MAJORVERSION) \
	"." _VERSIONINFO_STR(VERSIONINFO_MINORVERSION) \
	"." _VERSIONINFO_STR(VERSIONINFO_BUGFIXVERSION)
