#pragma once

#define VERSIONINFO_MAJORVERSION 1
#define VERSIONINFO_MINORVERSION 3
#define VERSIONINFO_BUGFIXVERSION 2

#define VERSIONINFO_COPYRIGHT_YEAR "2026"
#define VERSIONINFO_COPYRIGHT_NAME "Anthony Kleine"

#define VERSIONINFO_FILE_DESCRIPTION "Myst IV: Revolution"
#define VERSIONINFO_COMPANY_NAME "TOMYSSHADOW"
#define VERSIONINFO_PRODUCT_NAME "M4Revolution"
#define VERSIONINFO_FILE_NAME VERSIONINFO_PRODUCT_NAME ".exe"

#define VERSIONINFO_LANG_ID 0x1009
#define VERSIONINFO_CHARSET_ID 1200

#define _VERSIONINFO_STR(s) #s
#define _VERSIONINFO_XSTR(s) _VERSIONINFO_STR(s)

#if defined(VERSIONINFO_MAJORVERSION) \
	&& defined(VERSIONINFO_MINORVERSION) \
	&& defined(VERSIONINFO_BUGFIXVERSION)
	#define VERSIONINFO_VERSION \
		_VERSIONINFO_XSTR(VERSIONINFO_MAJORVERSION) \
		"." _VERSIONINFO_XSTR(VERSIONINFO_MINORVERSION) \
		"." _VERSIONINFO_XSTR(VERSIONINFO_BUGFIXVERSION)
#endif
