#pragma once
#include "versioninfo.h"

#ifdef RC_INVOKED
VS_VERSION_INFO VERSIONINFO
 FILEVERSION VERSIONINFO_MAJORVERSION,VERSIONINFO_MINORVERSION,VERSIONINFO_BUGFIXVERSION,0
 PRODUCTVERSION VERSIONINFO_MAJORVERSION,VERSIONINFO_MINORVERSION,VERSIONINFO_BUGFIXVERSION,0
 FILEFLAGSMASK 0x3fL
#ifdef _DEBUG
 FILEFLAGS 0x1L
#else
 FILEFLAGS 0x0L
#endif
 FILEOS 0x40004L
 FILETYPE 0x1L
 FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "100904b0"
        BEGIN
            VALUE "CompanyName", VERSIONINFO_COMPANY_NAME
            VALUE "FileDescription", VERSIONINFO_FILE_DESCRIPTION
            VALUE "FileVersion", VERSIONINFO_VERSION ".0"
            VALUE "InternalName", VERSIONINFO_FILE_NAME
            VALUE "LegalCopyright", "Copyright (C) " VERSIONINFO_COPYRIGHT_NAME " " VERSIONINFO_COPYRIGHT_YEAR
            VALUE "OriginalFilename", VERSIONINFO_FILE_NAME
            VALUE "ProductName", VERSIONINFO_PRODUCT_NAME
            VALUE "ProductVersion", VERSIONINFO_VERSION ".0"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x1009, 1200
    END
END
#else
    constexpr bool _versioninfoCurrentYear() {
	    return VERSIONINFO_COPYRIGHT_YEAR[0] == __DATE__[7]
		    && VERSIONINFO_COPYRIGHT_YEAR[1] == __DATE__[8]
		    && VERSIONINFO_COPYRIGHT_YEAR[2] == __DATE__[9]
		    && VERSIONINFO_COPYRIGHT_YEAR[3] == __DATE__[10];
    }

    static_assert(_versioninfoCurrentYear(), "VERSIONINFO_COPYRIGHT_YEAR mismatch");
#endif

